In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
iris=pd.read_csv("iris.csv")

In [3]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
features=iris.drop('species', axis=1)
features.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

#### Build the model

In [5]:
from sklearn.cluster import DBSCAN

In [6]:
model=DBSCAN(eps=0.5, min_samples=12, metric='euclidean')
model.fit(features)

DBSCAN(min_samples=12)

In [7]:
model.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0, -1,
        1, -1,  1,  1,  1,  1, -1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  1,  1,  1,  1,  1,  1,  1,
        1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
       -1,  2,  2, -1, -1, -1, -1, -1,  2,  2,  2, -1, -1,  2,  2, -1, -1,
       -1,  2, -1, -1,  1,  2, -1,  1,  1,  2, -1, -1, -1,  2,  1, -1, -1,
       -1,  2,  1,  2,  2,  2,  1,  2, -1,  2,  1,  2, -1,  1],
      dtype=int64)

In [8]:
features['labels']=model.labels_
features.head()

   sepal_length  sepal_width  petal_length  petal_width  labels
0           5.1          3.5           1.4          0.2       0
1           4.9          3.0           1.4          0.2       0
2           4.7          3.2           1.3          0.2       0
3           4.6          3.1           1.5          0.2       0
4           5.0          3.6           1.4          0.2       0

In [9]:
grp=features.groupby('labels')
grp.agg('mean')

        sepal_length  sepal_width  petal_length  petal_width
labels
-1          6.397143     2.962857      4.891429     1.657143
 0          4.973913     3.402174      1.471739     0.243478
 1          5.968000     2.814000      4.424000     1.420000
 2          6.600000     3.036842      5.452632     2.089474

In [10]:
iris_grp=iris.groupby('species')
iris_grp.agg('mean')

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

#### Evaluate the model

In [11]:
from sklearn.metrics import silhouette_score

In [14]:
silhouette_score(features.drop('labels', axis=1), features['labels'])

0.3286036630954711