In [1]:
import pandas as pd

In [2]:
udf=pd.read_csv('C://Users/harik/python pratice/Universities.csv', index_col='Univ')
udf

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown         1310     89      22       13     22704        94
CalTech       1415    100      25        6     63575        81
CMU           1260     62      59        9     25026        72
Columbia      1310     76      24       12     31510        88
Cornell       1280     83      33       13     21864        90
Dartmouth     1340     89      23       10     32162        95
Duke          1315     90      30       12     31585        95
Georgetown    1255     74      24       12     20126        92
Harvard       1400     91      14       11     39525        97
JohnsHopkins  1305     75      44        7     58691        87
MIT           1380     94      30       10     34870        91
Northwestern  1260     85      39       11     28052        89
NotreDame     1255     81      42       13     15122        94
PennState     1081     38      54       18     10185        80
Princeton     1375     91      14        8     30220        95
Purdue        1005     28      90       19      9066        69
Stanford      1360     90      20       12     36450        93
TexasA&M      1075     49      67       25      8704        67
UCBerkeley    1240     95      40       17     15140        78
UChicago      1290     75      50       13     38380        87
UMichigan     1180     65      68       16     15470        85
UPenn         1285     80      36       11     27553        90
UVA           1225     77      44       14     13349        92
UWisconsin    1085     40      69       15     11857        71
Yale          1375     95      19       11     43514        96

#### Standardize

In [3]:
from sklearn.preprocessing import StandardScaler

In [4]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(udf)
scaled_data

array([[ 0.41028362,  0.6575195 , -0.88986682,  0.07026045, -0.33141256,
         0.82030265],
       [ 1.39925928,  1.23521235, -0.73465749, -1.68625071,  2.56038138,
        -0.64452351],
       [-0.06065717, -0.76045386,  1.02438157, -0.93346022, -0.16712136,
        -1.65863393],
       [ 0.41028362, -0.02520842, -0.78639393, -0.18066972,  0.29164871,
         0.14422904],
       [ 0.12771914,  0.34241431, -0.32076595,  0.07026045, -0.39084607,
         0.36958691],
       [ 0.69284809,  0.6575195 , -0.83813038, -0.68253005,  0.33778044,
         0.93298158],
       [ 0.4573777 ,  0.71003703, -0.47597528, -0.18066972,  0.29695528,
         0.93298158],
       [-0.10775125, -0.13024348, -0.78639393, -0.18066972, -0.51381683,
         0.59494478],
       [ 1.25797704,  0.76255456, -1.30375836, -0.43159988,  0.85874344,
         1.15833946],
       [ 0.36318954, -0.07772595,  0.24833493, -1.43532055,  2.21481798,
         0.0315501 ],
       [ 1.06960072,  0.92010716, -0.47597528, -0.68253005,  0.52938275,
         0.48226584],
       [-0.06065717,  0.44744937, -0.01034729, -0.43159988,  0.04698077,
         0.25690797],
       [-0.10775125,  0.23737924,  0.14486204,  0.07026045, -0.86787073,
         0.82030265],
       [-1.7466252 , -2.02087462,  0.76569936,  1.32491127, -1.21718409,
        -0.75720245],
       [ 1.02250664,  0.76255456, -1.30375836, -1.18439038,  0.20037583,
         0.93298158],
       [-2.46245521, -2.54604994,  2.6282113 ,  1.57584144, -1.29635802,
        -1.99667073],
       [ 0.88122441,  0.71003703, -0.9933397 , -0.18066972,  0.64117435,
         0.70762371],
       [-1.8031381 , -1.44318177,  1.43827311,  3.08142243, -1.32197103,
        -2.22202861],
       [-0.24903349,  0.97262469,  0.04138915,  1.07398111, -0.86659715,
        -0.98256032],
       [ 0.2219073 , -0.07772595,  0.55875358,  0.07026045,  0.77772991,
         0.0315501 ],
       [-0.81416244, -0.60290126,  1.49000956,  0.82305094, -0.84324827,
        -0.19380777],
       [ 0.17481322,  0.18486171, -0.16555662, -0.43159988,  0.01167444,
         0.36958691],
       [-0.39031573,  0.02730912,  0.24833493,  0.32119061, -0.99331788,
         0.59494478],
       [-1.70894994, -1.91583956,  1.541746  ,  0.57212078, -1.09888311,
        -1.77131286],
       [ 1.02250664,  0.97262469, -1.04507615, -0.43159988,  1.14098185,
         1.04566052]])

In [5]:
scaled_df=pd.DataFrame(scaled_data, columns=udf.columns, index=udf.index)
scaled_df

                   SAT     Top10    Accept   SFRatio  Expenses  GradRate
Univ
Brown         0.410284  0.657519 -0.889867  0.070260 -0.331413  0.820303
CalTech       1.399259  1.235212 -0.734657 -1.686251  2.560381 -0.644524
CMU          -0.060657 -0.760454  1.024382 -0.933460 -0.167121 -1.658634
Columbia      0.410284 -0.025208 -0.786394 -0.180670  0.291649  0.144229
Cornell       0.127719  0.342414 -0.320766  0.070260 -0.390846  0.369587
Dartmouth     0.692848  0.657519 -0.838130 -0.682530  0.337780  0.932982
Duke          0.457378  0.710037 -0.475975 -0.180670  0.296955  0.932982
Georgetown   -0.107751 -0.130243 -0.786394 -0.180670 -0.513817  0.594945
Harvard       1.257977  0.762555 -1.303758 -0.431600  0.858743  1.158339
JohnsHopkins  0.363190 -0.077726  0.248335 -1.435321  2.214818  0.031550
MIT           1.069601  0.920107 -0.475975 -0.682530  0.529383  0.482266
Northwestern -0.060657  0.447449 -0.010347 -0.431600  0.046981  0.256908
NotreDame    -0.107751  0.237379  0.144862  0.070260 -0.867871  0.820303
PennState    -1.746625 -2.020875  0.765699  1.324911 -1.217184 -0.757202
Princeton     1.022507  0.762555 -1.303758 -1.184390  0.200376  0.932982
Purdue       -2.462455 -2.546050  2.628211  1.575841 -1.296358 -1.996671
Stanford      0.881224  0.710037 -0.993340 -0.180670  0.641174  0.707624
TexasA&M     -1.803138 -1.443182  1.438273  3.081422 -1.321971 -2.222029
UCBerkeley   -0.249033  0.972625  0.041389  1.073981 -0.866597 -0.982560
UChicago      0.221907 -0.077726  0.558754  0.070260  0.777730  0.031550
UMichigan    -0.814162 -0.602901  1.490010  0.823051 -0.843248 -0.193808
UPenn         0.174813  0.184862 -0.165557 -0.431600  0.011674  0.369587
UVA          -0.390316  0.027309  0.248335  0.321191 -0.993318  0.594945
UWisconsin   -1.708950 -1.915840  1.541746  0.572121 -1.098883 -1.771313
Yale          1.022507  0.972625 -1.045076 -0.431600  1.140982  1.045661

#### Normalize

In [6]:
from sklearn.preprocessing import MinMaxScaler

In [7]:
norm = MinMaxScaler()
norm_data = norm.fit_transform(udf)
norm_data

array([[0.74390244, 0.84722222, 0.10526316, 0.36842105, 0.25514388,
        0.9       ],
       [1.        , 1.        , 0.14473684, 0.        , 1.        ,
        0.46666667],
       [0.62195122, 0.47222222, 0.59210526, 0.15789474, 0.29746132,
        0.16666667],
       [0.74390244, 0.66666667, 0.13157895, 0.31578947, 0.41562939,
        0.7       ],
       [0.67073171, 0.76388889, 0.25      , 0.36842105, 0.23983525,
        0.76666667],
       [0.81707317, 0.84722222, 0.11842105, 0.21052632, 0.4275118 ,
        0.93333333],
       [0.75609756, 0.86111111, 0.21052632, 0.31578947, 0.41699623,
        0.93333333],
       [0.6097561 , 0.63888889, 0.13157895, 0.31578947, 0.20816096,
        0.83333333],
       [0.96341463, 0.875     , 0.        , 0.26315789, 0.56169926,
        1.        ],
       [0.73170732, 0.65277778, 0.39473684, 0.05263158, 0.91099123,
        0.66666667],
       [0.91463415, 0.91666667, 0.21052632, 0.21052632, 0.47686392,
        0.8       ],
       [0.62195122, 0.79166667, 0.32894737, 0.26315789, 0.35260885,
        0.73333333],
       [0.6097561 , 0.73611111, 0.36842105, 0.36842105, 0.11696525,
        0.9       ],
       [0.18536585, 0.13888889, 0.52631579, 0.63157895, 0.02699058,
        0.43333333],
       [0.90243902, 0.875     , 0.        , 0.10526316, 0.3921197 ,
        0.93333333],
       [0.        , 0.        , 1.        , 0.68421053, 0.00659729,
        0.06666667],
       [0.86585366, 0.86111111, 0.07894737, 0.31578947, 0.50565873,
        0.86666667],
       [0.17073171, 0.29166667, 0.69736842, 1.        , 0.        ,
        0.        ],
       [0.57317073, 0.93055556, 0.34210526, 0.57894737, 0.11729329,
        0.36666667],
       [0.69512195, 0.65277778, 0.47368421, 0.36842105, 0.54083213,
        0.66666667],
       [0.42682927, 0.51388889, 0.71052632, 0.52631579, 0.12330739,
        0.6       ],
       [0.68292683, 0.72222222, 0.28947368, 0.26315789, 0.34351479,
        0.76666667],
       [0.53658537, 0.68055556, 0.39473684, 0.42105263, 0.0846531 ,
        0.83333333],
       [0.19512195, 0.16666667, 0.72368421, 0.47368421, 0.05746205,
        0.13333333],
       [0.90243902, 0.93055556, 0.06578947, 0.26315789, 0.63439704,
        0.96666667]])

In [8]:
norm_df=pd.DataFrame(scaled_data, columns=udf.columns, index=udf.index)
norm_df

                   SAT     Top10    Accept   SFRatio  Expenses  GradRate
Univ
Brown         0.410284  0.657519 -0.889867  0.070260 -0.331413  0.820303
CalTech       1.399259  1.235212 -0.734657 -1.686251  2.560381 -0.644524
CMU          -0.060657 -0.760454  1.024382 -0.933460 -0.167121 -1.658634
Columbia      0.410284 -0.025208 -0.786394 -0.180670  0.291649  0.144229
Cornell       0.127719  0.342414 -0.320766  0.070260 -0.390846  0.369587
Dartmouth     0.692848  0.657519 -0.838130 -0.682530  0.337780  0.932982
Duke          0.457378  0.710037 -0.475975 -0.180670  0.296955  0.932982
Georgetown   -0.107751 -0.130243 -0.786394 -0.180670 -0.513817  0.594945
Harvard       1.257977  0.762555 -1.303758 -0.431600  0.858743  1.158339
JohnsHopkins  0.363190 -0.077726  0.248335 -1.435321  2.214818  0.031550
MIT           1.069601  0.920107 -0.475975 -0.682530  0.529383  0.482266
Northwestern -0.060657  0.447449 -0.010347 -0.431600  0.046981  0.256908
NotreDame    -0.107751  0.237379  0.144862  0.070260 -0.867871  0.820303
PennState    -1.746625 -2.020875  0.765699  1.324911 -1.217184 -0.757202
Princeton     1.022507  0.762555 -1.303758 -1.184390  0.200376  0.932982
Purdue       -2.462455 -2.546050  2.628211  1.575841 -1.296358 -1.996671
Stanford      0.881224  0.710037 -0.993340 -0.180670  0.641174  0.707624
TexasA&M     -1.803138 -1.443182  1.438273  3.081422 -1.321971 -2.222029
UCBerkeley   -0.249033  0.972625  0.041389  1.073981 -0.866597 -0.982560
UChicago      0.221907 -0.077726  0.558754  0.070260  0.777730  0.031550
UMichigan    -0.814162 -0.602901  1.490010  0.823051 -0.843248 -0.193808
UPenn         0.174813  0.184862 -0.165557 -0.431600  0.011674  0.369587
UVA          -0.390316  0.027309  0.248335  0.321191 -0.993318  0.594945
UWisconsin   -1.708950 -1.915840  1.541746  0.572121 -1.098883 -1.771313
Yale          1.022507  0.972625 -1.045076 -0.431600  1.140982  1.045661